OrdererOrgs:
 - Name: Orderer
   Domain: upstac.com
   Specs:
      - Hostname: orderer
PeerOrgs:
 - Name: hospitalA
   Domain: hospitalA.upstac.com
   EnableNodeOUs: true

   # ---------------------------------------------------------------------------
   # "CA"
   # ---------------------------------------------------------------------------
   # Uncomment this section to enable the explicit definition of the CA for this
   # organization.  This entry is a Spec.  See "Specs" section below for details.
   # ---------------------------------------------------------------------------
   CA:
      Hostname: ca # implicitly ca.hospitalA.upstac.com

   # ---------------------------------------------------------------------------
   # "Template"
   # ---------------------------------------------------------------------------
   # Allows for the definition of 1 or more hosts that are created sequentially
   # from a template. By default, this looks like "peer%d" from 0 to Count-1.
   # You may override the number of nodes (Count), the starting index (Start)
   # or the template used to construct the name (Hostname).
   #
   # Note: Template and Specs are not mutually exclusive.  You may define both
   # sections and the aggregate nodes will be created for you.  Take care with
   # name collisions
   # ---------------------------------------------------------------------------
   Template:
      Count: 2

   # ---------------------------------------------------------------------------
   # "Users"
   # ---------------------------------------------------------------------------
   # Count: The number of user accounts _in addition_ to Admin
   # ---------------------------------------------------------------------------
   Users:
      Count: 1

 - Name: hospitalB
   Domain: hospitalB.upstac.com
   EnableNodeOUs: true

   # ---------------------------------------------------------------------------
   # "CA"
   # ---------------------------------------------------------------------------
   # Uncomment this section to enable the explicit definition of the CA for this
   # organization.  This entry is a Spec.  See "Specs" section below for details.
   # ---------------------------------------------------------------------------
   CA:
      Hostname: ca # implicitly ca.hospitalB.upstac.com

   # ---------------------------------------------------------------------------
   # "Template"
   # ---------------------------------------------------------------------------
   # Allows for the definition of 1 or more hosts that are created sequentially
   # from a template. By default, this looks like "peer%d" from 0 to Count-1.
   # You may override the number of nodes (Count), the starting index (Start)
   # or the template used to construct the name (Hostname).
   #
   # Note: Template and Specs are not mutually exclusive.  You may define both
   # sections and the aggregate nodes will be created for you.  Take care with
   # name collisions
   # ---------------------------------------------------------------------------
   Template:
      Count: 2

   # ---------------------------------------------------------------------------
   # "Users"
   # ---------------------------------------------------------------------------
   # Count: The number of user accounts _in addition_ to Admin
   # ---------------------------------------------------------------------------
   Users:
      Count: 1

 - Name: government
   Domain: government.upstac.com
   EnableNodeOUs: true

   # ---------------------------------------------------------------------------
   # "CA"
   # ---------------------------------------------------------------------------
   # Uncomment this section to enable the explicit definition of the CA for this
   # organization.  This entry is a Spec.  See "Specs" section below for details.
   # ---------------------------------------------------------------------------
   CA:
      Hostname: ca # implicitly ca.government.upstac.com

   # ---------------------------------------------------------------------------
   # "Template"
   # ---------------------------------------------------------------------------
   # Allows for the definition of 1 or more hosts that are created sequentially
   # from a template. By default, this looks like "peer%d" from 0 to Count-1.
   # You may override the number of nodes (Count), the starting index (Start)
   # or the template used to construct the name (Hostname).
   #
   # Note: Template and Specs are not mutually exclusive.  You may define both
   # sections and the aggregate nodes will be created for you.  Take care with
   # name collisions
   # ---------------------------------------------------------------------------
   Template:
      Count: 2

   # ---------------------------------------------------------------------------
   # "Users"
   # ---------------------------------------------------------------------------
   # Count: The number of user accounts _in addition_ to Admin
   # ---------------------------------------------------------------------------
   Users:
      Count: 1