# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  peer0.insurance.upstac.com:
  
networks:
  registration:

services:

  peer0.insurance.upstac.com:
    container_name: peer0.insurance.upstac.com
    extends:
      file: docker-base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.insurance.upstac.com
      - CORE_PEER_ADDRESS=peer0.insurance.upstac.com:21051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:21051
      - CORE_PEER_CHAINCODEADDRESS=peer0.insurance.upstac.com:21053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:21053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.insurance.upstac.com:21051
      - CORE_PEER_LOCALMSPID=insuranceMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./insurance-artifacts/crypto-config/peerOrganizations/insurance.upstac.com/peers/peer0.insurance.upstac.com/msp:/etc/hyperledger/fabric/msp
        - ./insurance-artifacts/crypto-config/peerOrganizations/insurance.upstac.com/peers/peer0.insurance.upstac.com/tls:/etc/hyperledger/fabric/tls
        - peer0.insurance.upstac.com:/var/hyperledger/production
    ports:
      - 21051:21051
      - 21053:21053
    networks:
      - registration

  insurancecli:
    container_name: insurancecli
    image: hyperledger/fabric-tools:1.4.3
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=insurancecli
      - CORE_PEER_ADDRESS=peer0.insurance.upstac.com:21051
      - CORE_PEER_LOCALMSPID=insuranceMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/insurance.upstac.com/peers/peer0.insurance.upstac.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/insurance.upstac.com/peers/peer0.insurance.upstac.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/insurance.upstac.com/peers/peer0.insurance.upstac.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/insurance.upstac.com/users/Admin@insurance.upstac.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode/
        - ./insurance-artifacts/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./crypto-config/peerOrganizations/hospitalA.upstac.com:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hospitalA.upstac.com
        - ./crypto-config/peerOrganizations/hospitalB.upstac.com:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hospitalB.upstac.com
        - ./crypto-config/peerOrganizations/government.upstac.com:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/government.upstac.com
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
    depends_on:
      - peer0.insurance.upstac.com
    networks:
      - registration
